### ISSUE TITLE
Can pesterchum maintain private conversations?

### ISSUE THREAD

**Issue by luminaryIridescence** [illuminatedwax/pesterchum#150]
I was just wonder if what you write will be only for your eyes and that of who you are chatting with. I have to know if it's COMPLETELY private.

**Comment by arcaneAgilmente** [comment]
I would assume that the servers administrator (ghostDunk) would be able to
see your conversations (feel free to correct if wrong gD) but other than
that unless logs are shared nothing can be seen by anybody else. Avoid
discussing illegal/immoral topics and you should be okay.

**Comment by illuminatedwax** [comment]
I cannot see individual conversations or memo chat unless I am present in
the memo. To do otherwise would be an invasion of privacy. Exceptions are
calsprite,I can see everything people send it. Occasionally I might run a
test server that does log all conversions, but in that case you WILL get a
notification saying so ion logging in.

**Comment by luminaryIridescence** [comment]
okay. thank you for sharing that with me!
