### ISSUE TITLE
I'm getting "Errno 10061"

### ISSUE THREAD

**Issue by giraffeinthehat** [illuminatedwax/pesterchum#3]
Ok. Well. I haven't been able to connect to the server with this incarnation of pesterchum, or with the previous one. My OS is Windows 7. My java is up to date,  I've set rules that open ports 6660-6669 in my Windows firewall, in the hopes that that would fix my problem. It hasn't.

I get this http://img857.imageshack.us/img857/8427/errormessageforpchum.png . I would like to know the specifics of what Error 10061 consists of (other than my computer clearly being a douche), and what I can do to fix it. So um...please help? OTL

**Comment by kiooeht** [comment]
From what I've managed to find in a quick Google search:
- [MSDN](http://social.msdn.microsoft.com/forums/en-US/wcf/thread/58e420e9-43a3-4119-b541-d18158038e36/)
- [Stack Overflow](http://stackoverflow.com/questions/4532335/errno-10061-no-connection-could-be-made-because-the-target-machine-actively-ref)

it most likely has something to do with firewall settings either on your computer, your router, or your ISP.

You said you you'd opened port 6660-6669 on your firewall, pesterchum runs through port 6667, try explicitly opening that port in your firewall and possibly your router if you have access to it.

If it still doesn't work, try connecting to the server through a normal irc client (mIRC, XChat, etc.) and make sure that's able to connect properly (irc.mindfang.org, port 6667). If that works, make sure your "server" and "port" lines in pesterchum.js are those values (if "server" and "port" don't show up in pesterchum.js then they'll just default to those correct values). If that still doesn't work, then I'm not sure what else you can do =/ sorry.

**Comment by Spambrah** [comment]
Hi - I am having the same problem - but I dont know how to fix it.
I've allowed traffic for pesterchum (the program I'm getting the error for) but it's still not working.
Any ideas?
