### ISSUE TITLE
BLUH

### ISSUE THREAD

**Issue by atriumDefendor** [illuminatedwax/pesterchum#9]
So my only problem is everytime I try to access pesterchum it says my tag I made today is already taken even though im not using it so it keeps adding me as a new member but the weirdest thing is my chums are still on my list

**Comment by ashen-dawn** [comment]
Your chums still being on the list is normal and intentional because (Unlike 2.5) Pesterchum 3.14 stores your chumroll in the pesterchum.js file which is independent of a profile.  The profiles are stored elsewhere.  Could you access your pestertag before or has it been doing this from the very beginning.  If it just started doing it after having worked for a while, then it could be from this bug here: https://github.com/illuminatedwax/pesterchum/issues/12.

If it's been doing this ever since you started using Pesterchum then I don't know what to tell you.  There is a limit to my knowledge, even if I don't like to tell myself that there is.

**Comment by atriumDefendor** [comment]
thank you for the help it was really just a stupid mistake on my part
